sudo: required
language: node_js
node_js:
  - "14"
services:
  - docker

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

script:
  - docker build -t judicaelandria/check:v2 .
  - docker tag judicaelandria/check:v2 registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    docker push judicaelandria/check:v2;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --remote docker
  on:
    branch: master